### ISSUE TITLE
404 Link

### ISSUE THREAD

**Issue by linuxbsdfreak** [joatmon08/gitops-hashicups#1]
Hi @pcmccarron @joatmon08 

Nice demo https://www.youtube.com/watch?v=QXRsvyyHYxQ 

However this link https://github.com/pcmccarron/tf-cloud-repo/tree/rosemary/gitops is broken in the README. 

Could i have a look at the repo ?

**Comment by joatmon08** [comment]
Let me ask - there are a few things that we might have to clean up in it but stay tuned!

**Comment by joatmon08** [comment]
Added to https://github.com/joatmon08/gitops-hashicups/tree/main/infrastructure!
